FROM nvidia/cuda:12.3.1-base-ubuntu20.04 as build

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG DEBIAN_FRONTEND=noninteractive
ARG WORKSPACE_DIR=/workspaces/IndigoLeague

WORKDIR ${WORKSPACE_DIR}

RUN addgroup --gid $GROUP_ID usergroup \
    && adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user

COPY requirements.txt setup.py ${WORKSPACE_DIR}/

RUN apt-get update && apt-get install -y  \
    curl  \
    g++ \
    python3.8 \
    python3-pip \
    libcusparse-11-2 && \
    rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python && \
    pip install --upgrade pip && \
    cd ${WORKSPACE_DIR} && \
    pip install -r ${WORKSPACE_DIR}/requirements.txt

COPY data ${WORKSPACE_DIR}/data
COPY indigo_league ${WORKSPACE_DIR}/indigo_league

RUN pip install ${WORKSPACE_DIR}/.

USER user

CMD ["python", "-m", "indigo_league.main"]
