FROM node:latest as showdown

ADD ./third_party/pokemon-showdown /showdown/pokemon-showdown

EXPOSE 8000

WORKDIR /showdown/pokemon-showdown

RUN mkdir -p /showdown/pokemon-showdown/logs/repl/ && \
    cp /showdown/pokemon-showdown/config/config-example.js /showdown/pokemon-showdown/config/config.js && \
    npm install

CMD [ "node", "pokemon-showdown", "start", "--no-security" ]